{% set version = "1.16" %}

package:
  name: lightfm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lightfm/lightfm-{{ version }}.tar.gz
  sha256: 41950fd8affde192c10b517148aa7f6d016ae2f75a2ec1187335f1c4d21876ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - scipy >=0.17
    - requests
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.17
    - requests

test:
  imports:
    # ensure OpenMP backend is used on linux
    - lightfm._lightfm_fast_openmp  # [linux]
    - lightfm
    - lightfm.lightfm

about:
  home: https://github.com/lyst/lightfm
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python implementation of LightFM, a hybrid recommendation algorithm.
  description: |
    LightFM is a Python implementation of a number of popular recommendation
    algorithms for both implicit and explicit feedback, including efficient
    implementation of BPR and WARP ranking losses. It's easy to use,
    fast (via multithreaded model estimation), and produces high quality results.
  doc_url: http://lyst.github.io/lightfm/docs/home.html
  dev_url: https://github.com/lyst/lightfm

extra:
  recipe-maintainers:
    - maciejkula
    - rth
