travis:
  secure:
    BINSTAR_TOKEN: cBFCgq/ZvmhGkVghgl85grsAEg6i1HYvaPt5xETeaVDcm/MDU+M9EOhACILFzly2VuZdfl3TkUdXDzCECKehV9f63EQjadpk6a/heGnGD+qji6/yYkc/wUrlUA9tmMC0kttv4Yjny27qeaKqpKaIiQCBZoNxcP9RjsURbpybY1YrM75Wu7cxIZI9PL5eHf1XgugpotRQ3wCPv0tV8C/PmRm9Z9k4RgB5HVbFHXwatIO3+xe9T6nXJsT6B+UhrZI3j6nKcsO4zUVvr2VZXJXpO0qNoQr4cGPQ+bfz4j7TIx7z/8V0kzbDq1RuNnb5huRUZPMumn0uOxNcL5tMqBwcn2rOS8gqd1I5kaFn/XGQslrmL16bKvMN0T+tghq4ZrvK9l7VoHQrXllXKnYJXLdVVCZ1HFvmJ1PrtrSBhibwGnQouKnMN3kXOufmh6U+oVbLqWhezjV/zTisoBFeFwI/PE5vgAHk9towclGewVAHVkkvmPuvd4xmyEefq3cFYWBP52YL4na3uYt8cLWapPlcpPvbst/GFTIYbVbX55rq9lJYe8CncCovimTM4aoudOXt5W0zUB3BL4e+RZIr3FuUS/rTmUIEM6+eu6p7UBKO5q7rtjr1dnoid5IqOxUXfBuWcKMffmwrRdwafX24fyFzD9NtzJqF8zZt7YrvOUo/k0A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
